
"""
    This class implements the packet data structure with
    associated properties.
"""


class Packet:
    """ """

    def __init__(self):
        self.ue_id = 0
        self.packet_id = 0
        self.priority = 0
        self.pending_size = 0.0
        self.kpi_reliability = 0.0
        self.generation_time = 0  # tick of generation
        self.arrival_time = 0  # from generation time, in ticks
        self.n_transmissions = 0  # Number of times the packet has been transmitted
        self.packet_size = None  # Original packet size
        self.packet_size_on = None  # Packet size for ON collection
        self.packet_size_standby = None  # Packet size for Standby Collection
        self.packet_size_optimization = None  # Packet size for Optimization
        self.packet_duration_s = None  # Packet duration in seconds
        self.packet_duration_tick = None  # Packet duration in tick
        self.data_to_be_sent = 0  # Remaining data to be sent, i.e remaining packet size
        self.data_to_be_forwarded_bool = False  # True if the packet was not generated by the UE itself
        self.num_tx = 0  # Number of transmissions
        self.max_n_retx = 0  # Maximum number of retransmissions
        self.data_rx_from_ue = None
        self.packet_id_rx_from_ue = None
        self.ack_rx = False
        self.retransmission_of_packets = False
        self.discarded_packet = True
        self.unicast = False
        self.sequence_number = None

        ############################ Multi-Hop Implementation ############################
        self.generated_by_ue = None
        self.packet_id_generator = None
        self.hop_count = 0
        self.tick_packet_generated_by_ue = None
        ########################## RL Implementation ############################
        self.address = None
        ########################## End RL Implementation ########################


    def update_data_to_be_sent(self, sent_data: float):
        """
        Update the remaining data (in MB) to be sent for this packet.

        Args:
            sent_data (float): Amount of data (in MB) that was transmitted in this step.

        Returns:
            int: 1 if the packet has been fully transmitted, 0 otherwise.
        """
        self.data_to_be_sent = max(0, int(self.data_to_be_sent - sent_data))
        if self.data_to_be_sent:
            return 0
        return 1

    def update_pending_data(self, sent_data: float):
        """
        Update the pending data for this packet based on the amount of data sent.

        Args:
            sent_data (float): Amount of data (in MB) sent during this tick.

        Returns:
            float: The remaining pending data size (MB).
        """
        remove_pending_size = min(self.pending_size, sent_data)
        self.pending_size -= remove_pending_size
        self.pending_size = round(self.pending_size, 1)
        self.data_to_be_sent -= remove_pending_size
        self.data_to_be_sent = round(self.data_to_be_sent, 1)
        return self.pending_size

    def set_data_to_be_sent(self, data_to_be_sent):
        """
        Set the total amount of data (in MB) to be sent for this packet.

        Args:
            data_to_be_sent: The data amount to assign to this packet.

        Returns:
            None
        """
        self.data_to_be_sent = data_to_be_sent

    def get_data_to_be_sent(self):
        """
        Get the total remaining data (in MB) to be sent for this packet.

        Returns:
            float: Remaining data amount.
        """
        return self.data_to_be_sent

    def get_transmission_counter(self):
        """
        Get the number of transmissions made for this packet.

        Returns:
            int: Number of transmissions so far.
        """
        return self.n_transmissions

    def increment_transmission_counter(self):
        """
        Increment the counter tracking the number of transmissions for this packet.

        Returns:
            None
        """
        self.n_transmissions += 1

    def set_ue_id(self, input_ue_id: int):
        """
        Set the ID of the UE transmitting this packet.

        Args:
            input_ue_id (int): ID of the transmitting UE.

        Returns:
            None
        """
        self.ue_id = input_ue_id

    def get_ue_id(self):
        """
        Get the ID of the UE transmitting this packet.

        Returns:
            int: UE ID.
        """
        return self.ue_id

    def set_id(self, input_packet_id: int):
        """
        Set the unique ID of this packet.

        Args:
            input_packet_id (int): Packet identifier.

        Returns:
            None
        """
        self.packet_id = input_packet_id

    def get_id(self):
        """
        Get the unique ID of this packet.

        Returns:
            int: Packet identifier.
        """
        return self.packet_id

    def set_data_rx_from_ue(self, data_rx_from_ue: int):
        """
        Set the ID of the UE from which this packet has been received.

        Args:
            data_rx_from_ue (int): ID of the transmitting UE.

        Returns:
            None
        """
        self.data_rx_from_ue = data_rx_from_ue

    def get_data_rx_from_ue(self):
        """
        Get the ID of the UE from which this packet was received.

        Returns:
            int: UE ID.
        """
        return self.data_rx_from_ue

    def set_packet_id_rx_from_ue(self, packet_id_rx_from_ue: int):
        """
        Set the packet ID received from a given UE.

        Args:
            packet_id_rx_from_ue (int): ID of the received packet.

        Returns:
            None
        """
        self.packet_id_rx_from_ue = packet_id_rx_from_ue

    def get_packet_id_rx_from_ue(self):
        """
        Get the packet ID received from a given UE.

        Returns:
            int: Packet ID.
        """
        return self.packet_id_rx_from_ue

    def set_size(self, input_size: int):
        """
        Set the size (in bits or bytes) of this packet.

        Args:
            input_size (int): Packet size value.

        Returns:
            None
        """
        self.packet_size = input_size

    def get_size(self):
        """
        Get the size of this packet.

        Returns:
            int: Packet size.
        """
        return self.packet_size

    def set_size_on(self, input_size: int):
        """
        Set the packet size used during ON traffic type.

        Args:
            input_size (int): Packet size during ON traffic type.

        Returns:
            None
        """
        self.packet_size_on = input_size

    def get_size_on(self):
        """
        Get the packet size used during ON traffic type.

        Returns:
            int: Packet size for ON traffic.
        """
        return self.packet_size_on

    def set_size_standby(self, input_size: int):
        """
        Set the packet size used during standby traffic type.

        Args:
            input_size (int): Packet size during standby.

        Returns:
            None
        """
        self.packet_size_standby = input_size

    def get_size_standby(self):
        """
        Get the packet size used during standby traffic type.

        Returns:
            int: Packet size for standby traffic.
        """
        return self.packet_size_standby

    def set_arrival_time(self, input_arrival_time: int):
        """
        Set the time (tick) when this packet was received.

        Args:
            input_arrival_time (int): Simulation tick when packet arrived.

        Returns:
            None
        """
        self.arrival_time = input_arrival_time

    def get_arrival_time(self):
        """
        Get the time (tick) when this packet was received.

        Returns:
            int: Arrival time tick.
        """
        return self.arrival_time

    def set_generation_time(self, input_generation_time: int):
        """
        Set the time (tick) when this packet was generated.

        Args:
            input_generation_time (int): Simulation tick when packet was generated.

        Returns:
            None
        """
        self.generation_time = input_generation_time

    def get_generation_time(self):
        """
        Get the time (tick) when this packet was generated.

        Returns:
            int: Generation time tick.
        """
        return self.generation_time

    def set_data_to_be_forwarded_bool(self, input_data_to_be_forwarded_bool: bool):
        """
        Set whether this packet should be forwarded or not.

        Args:
            input_data_to_be_forwarded_bool (bool): True if packet will be forwarded.

        Returns:
            None
        """
        self.data_to_be_forwarded_bool = input_data_to_be_forwarded_bool

    def get_data_to_be_forwarded_bool(self):
        """
        Get whether this packet should be forwarded.

        Returns:
            bool: True if packet will be forwarded, False otherwise.
        """
        return self.data_to_be_forwarded_bool

    def set_data_unicast(self, input_data_unicast: bool):
        """
        Set whether the packet should be sent using unicast transmission.

        Args:
            input_data_unicast (bool): True if unicast, False otherwise.

        Returns:
            None
        """
        self.unicast = input_data_unicast

    def get_data_unicast(self):
        """
        Get whether the packet is sent using unicast transmission.

        Returns:
            bool: True if unicast, False otherwise.
        """
        return self.unicast

    def set_packet_duration_s(self, input_packet_duration_s: float):
        """
        Set the packet transmission duration in seconds.

        Args:
            input_packet_duration_s (float): Packet duration (s).

        Returns:
            None
        """
        self.packet_duration_s = input_packet_duration_s

    def get_packet_duration_s(self):
        """
        Get the packet transmission duration in seconds.

        Returns:
            float: Packet duration in seconds.
        """
        return self.packet_duration_s

    def set_packet_duration_tick(self, input_packet_duration_tick: int):
        """
        Set the packet duration in simulation ticks.

        Args:
            input_packet_duration_tick (int): Duration in ticks.

        Returns:
            None
        """
        self.packet_duration_tick = input_packet_duration_tick

    def get_packet_duration_tick(self):
        """
        Get the packet duration in simulation ticks.

        Returns:
            int: Packet duration (ticks).
        """
        return self.packet_duration_tick

    def set_num_tx(self, input_num_tx: int, input_enable_print: bool = None):
        """
        Set the number of transmission attempts made for this packet.

        Args:
            input_num_tx (int): Number of transmission attempts.
            input_enable_print (bool, optional): If True, print debug info. Defaults to None.

        Returns:
            None
        """
        self.num_tx = input_num_tx
        if input_enable_print:
            print('UE ', self.get_ue_id(), ' has updated the number of tx attempts of packet with ID ', self.get_id(),
                  ' to ', self.num_tx)

    def get_num_tx(self):
        """
        Get the number of transmission attempts made for this packet.

        Returns:
            int: Number of transmissions.
        """
        return self.num_tx

    def set_max_n_retx(self, input_max_n_retx: int):
        """
        Set the maximum number of retransmissions allowed for this packet.

        Args:
            input_max_n_retx (int): Maximum retransmission count.

        Returns:
            None
        """
        self.max_n_retx = input_max_n_retx

    def get_max_n_retx(self):
        """
        Get the maximum number of retransmissions allowed for this packet.

        Returns:
            int: Max retransmission count.
        """
        return self.max_n_retx

    def set_ack_rx(self, ack_rx: bool):
        """
        Set whether the ACK for this packet has been received.

        Args:
            ack_rx (bool): True if ACK received, False otherwise.

        Returns:
            None
        """
        self.ack_rx = ack_rx

    def get_ack_rx(self):
        """
        Get whether the ACK for this packet has been received.

        Returns:
            bool: True if ACK received, False otherwise.
        """
        return self.ack_rx

    def set_retransmission_packets(self, retransmission_bool: bool):
        """
        Set whether this packet has been retransmitted.

        Args:
            retransmission_bool (bool): True if retransmitted, False otherwise.

        Returns:
            None
        """
        self.retransmission_of_packets = retransmission_bool

    def get_retransmission_packets(self):
        """
        Get whether this packet has been retransmitted.

        Returns:
            bool: True if retransmitted, False otherwise.
        """
        return self.retransmission_of_packets

    def set_packet_discarded(self, discarded_bool: bool):
        """
        Set whether this packet has been discarded.

        Args:
            discarded_bool (bool): True if packet discarded, False otherwise.

        Returns:
            None
        """
        self.discarded_packet = discarded_bool

    def get_packet_discarded(self):
        """
        Get whether this packet has been discarded.

        Returns:
            bool: True if packet discarded, False otherwise.
        """
        return self.discarded_packet

    def set_sequence_number(self, input_sequence_number: int):
        """
        Set the sequence number of the packet.

        Args:
            input_sequence_number (int): Packet sequence number.

        Returns:
            None
        """
        self.sequence_number = input_sequence_number

    def get_sequence_number(self):
        """
        Get the sequence number of the packet.

        Returns:
            int: Packet sequence number.
        """
        return self.sequence_number

    def set_hop_count(self, hop_count: int):
        """
        Set the number of hops this packet has crossed.

        Args:
            hop_count (int): Hop count.

        Returns:
            None
        """
        self.hop_count = hop_count

    def get_hop_count(self):
        """
        Get the number of hops this packet has crossed.

        Returns:
            int: Hop count.
        """
        return self.hop_count

    def set_generated_by_ue(self, generated_by_ue: int):
        """
        Set the ID of the UE that originally generated this packet.

        Args:
            generated_by_ue (int): UE ID that generated the packet.

        Returns:
            None
        """
        self.generated_by_ue = generated_by_ue

    def get_generated_by_ue(self):
        """
        Get the ID of the UE that originally generated this packet.

        Returns:
            int: UE ID.
        """
        return self.generated_by_ue

    def set_generated_by_ue_time_instant_tick(self, tick_packet_generated_by_ue: int):
        """
        Set the simulation tick when the packet was generated by its original UE.

        Args:
            tick_packet_generated_by_ue (int): Generation tick.

        Returns:
            None
        """
        self.tick_packet_generated_by_ue = tick_packet_generated_by_ue

    def get_generated_by_ue_time_instant_tick(self):
        """
        Get the simulation tick when the packet was generated by its original UE.

        Returns:
            int: Generation tick.
        """
        return self.tick_packet_generated_by_ue

    def set_packet_id_generator(self, packet_id_generator: int):
        """
        Set the original packet ID before being forwarded.

        Args:
            packet_id_generator (int): Original packet ID.

        Returns:
            None
        """
        self.packet_id_generator = packet_id_generator

    def get_packet_id_generator(self):
        """
        Get the original packet ID before forwarding.

        Returns:
            int: Original packet ID.
        """
        return self.packet_id_generator

    def set_address(self, address):
        """
        Set the destination address of this packet.

        Args:
            address: Destination address (e.g., 'BS', UE ID, or broadcast).

        Returns:
            None
        """
        self.address = address

    def get_address(self):
        """
        Get the destination address of this packet.

        Returns:
            str | int: Destination address.
        """
        return self.address



